title: Lerntagebuch Modul Bibliotheks- und Archivinformatik
author: Joëlle
email: joelle.gantenbein@fhgr.ch
description: > # this means to ignore newlines
  Lerntagebuch im Kurs Bibliotheks- und Archivinformatik HS2021



show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
